### ISSUE TITLE
Very slow 

### ISSUE THREAD

**Issue by steven-murray** [terrencepreilly/darglint#111]
Hi and thanks for creating this awesome package!

I'm finding that running on a file with ~2000 lines is taking quite a long time (2-3min), which make it quite unpleasant when included as a pre-commit hook. I'm running with numpy style. 

Is this to be expected, or am I probably doing something wrong? My `.darglint` file is

```
[darglint]
docstring_style=numpy
enable=DAR104
ignore=DAR201
```

( I ignore DAR201 because I use a lot of docstringed properties).

**Comment by terrencepreilly** [comment]
Yes, this is to be expected.  See Issue #101 for a more detailed explanation.  But basically, I prioritized flexibility and completeness in the parser, and we can speed it up by either using a different parser, using a different parser on a subset of docstrings, or by rewriting the parser in Cython/Rust.

I haven't attempted them yet because I'm trying to stabilize it first, and -- unless users have very large files or use lots of arguments/exceptions/etc. -- it hasn't been much of an issue yet.

I'm going to close this as a duplicate, but I'll reference this with tracking issues once I get a chance to tackle the speed issue.  Since a couple people have brought it up, I'll try to prioritize it a bit more.
