### ISSUE TITLE
Add support for numpydoc format

### ISSUE THREAD

**Issue by Seirdy** [terrencepreilly/darglint#14]
This is possibly the best docstring linter I've seen.

The only thing holding me back from using it is the lack of support for the [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) docstring format. If support for this is included, darglint will support all 3 major Python docstring formats.

**Comment by terrencepreilly** [comment]
Seems reasonable.  I'm going to try rewriting Darglint's parser soon, so that it can handle stylistic errors, and so that it reports a more accurate representation of errors that exist instead of choking.  (See issues #12, #10, and #8.)

It may take me a little while to figure out how to update my parser.  When I do, I'll try to squeeze this in, as well.

**Comment by terrencepreilly** [comment]
I did end up implementing this, eventually.  There is a tracking issue: Issue #69.
