### ISSUE TITLE
Detecting completely missing docstrings

### ISSUE THREAD

**Issue by cristianmtr** [terrencepreilly/darglint#155]
Hey

this doesn't seem to catch completely missing docstrings. Am I missing something?

linting this

```python
def me(x):
    print(x)
```

does not find any problems

If I do add a basic docstring it detects the missing params

```python
def me(x):
    """smth"""
    print(x)
```

```
darglint -s sphinx -z full -v 2 /home/cristian/.config/JetBrains/PyCharm2020.3/scratches/scratch.py
/home/cristian/.config/JetBrains/PyCharm2020.3/scratches/scratch.py:me:1: DAR101: Missing parameter(s) in Docstring: - x
```

**Comment by terrencepreilly** [comment]
Yes, that's by design.  See [scope](https://github.com/terrencepreilly/darglint#scope) in the readme.  Since this is something covered by pydocstyle (See their [error codes](http://www.pydocstyle.org/en/stable/error_codes.html)), it's not added to darglint.  Darglint's purpose is to check if docstrings are accurate, not to enforce their presence.

We could probably add it as an disabled-by-default error, even if it's not really in scope for the program.  For the moment, though, it doesn't seem necessary.
