### ISSUE TITLE
Add support for epytext docstring format

### ISSUE THREAD

**Issue by xqt** [terrencepreilly/darglint#159]
Please add support for **epytext** docstring format which is a bit similar to reST (Sphinx) Format.
See also: [Different Python Docstring Formats](https://gist.github.com/nipunsadvilkar/fec9d2a40f9c83ea7fd97be59261c400)

**Comment by terrencepreilly** [comment]
It looks like the tooling for epytext is pretty out-of-date.  (epydoc hasn't been updated since [2008](http://epydoc.sourceforge.net/whatsnew.html).)  I've never heard of any projects using it.  Can you point to some large projects which use it? I'd rather focus on actually improving support for the formats we already support.

If it's important to a project of yours, you're welcome to fork darglint and write a new parser for this format.  Or, I'd accept PRs to move darglint towards a plugin model.  (Just be sure to communicate the plans for it beforehand, so that we can make sure it turns out clean.)
