### ISSUE TITLE
Two readmes?

### ISSUE THREAD

**Issue by sobolevn** [terrencepreilly/darglint#27]
I want to help you with some minor documentation features: like code hightlight, typos, etc.
But, for some reason there are two `README` files: `rst` and `md`. Why?

Which one can be deleted?

**Comment by terrencepreilly** [comment]
Thanks, I appreciate any help!

There are two `README` files because Github and PyPi accept different formats: Github accepts `README.md` and PyPi accepts `README.rst`.  In fact, I only ever edit the `README.md` file, and then generate the `README.rst` automatically generate it using [the `setup.py` prebuild command](https://github.com/terrencepreilly/darglint/blob/b5f07282f927fe9e040252c56c3a8c3ac84b8644/setup.py#L24).  It uses pandoc to convert between the formats, so that I only have to maintain one document.

So, when updating documentation, I update the `README.md` file, convert it, check that it renders correctly as HTML, and then commit it.  So, don't edit the `README.rst` file by hand.  If you'd like, you can delete it and I'll regenerate it when I merge it in (assuming that everything converts correctly.)

Feel free to offer suggestions/ask questions here.  For the moment, I'll close this issue.

**Comment by sobolevn** [comment]
The things is: GitHub supports `README.rst` as well 🙂 

Here's an example: https://github.com/sobolevn/django-split-settings/blob/master/README.rst
So, you can drop the `md` version.

**Comment by rpkilby** [comment]
Also, markdown is now supported by PyPI. Note that you must use twine for the upload process.
https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi/

**Comment by terrencepreilly** [comment]
Crazy! I don't know how I missed that.

@sobolevn Honestly, I would prefer to drop the `.rst` version, if both platforms support markdown.  But, if you have a good reason to prefer `rst` over `md`, go ahead.  I'll merge it in.
